### ISSUE TITLE
Implement top N cities in area query

### ISSUE THREAD

**Issue by Jaso5** [Jaso5/sm-group-project#6]
The top N populated cities in the world where N is provided by the user.
The top N populated cities in a continent where N is provided by the user.
The top N populated cities in a region where N is provided by the user.
The top N populated cities in a country where N is provided by the user.
The top N populated cities in a district where N is provided by the user.

**Comment by Michal-Mucha1** [comment]
As a user, I want to input a number and see a list of the most populated cities in an area of that length
